# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v12
        with:
          # Fetch the whole tree so git describe works
          fetch-depth: 0
          submodules: true
      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y git
          git clone https://github.com/nixos/nix
          cd /nix
          git checkout 2.3.7
          echo "extra-substituters = https://thefloweringash-armv7.cachix.org" >> /etc/nix/nix.conf && \
          echo "http-connections = 5" >> /etc/nix/nix.conf && \
          echo "trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= thefloweringash-armv7.cachix.org-1:v+5yzBD2odFKeXbmC+OPWVqx4WVoIVO6UXgnSAWFtso=" >> /etc/nix/nix.conf
          nix-build -E "builtins.fetchTarball https://github.com/NixOS/nixpkgs-channels/archive/nixos-19.09.tar.gz" || true
          echo "system = armv7l-linux" >> /etc/nix/nix.conf
          nix-build release.nix -A binaryTarball --arg nixpkgs "builtins.fetchTarball https://github.com/NixOS/nixpkgs-channels/archive/nixos-19.09.tar.gz" --arg systems '["armv7l-linux"]' --show-trace || true
